version: '3.8'

services:
  # Controller/Router
  gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - course-service
      - frontend

  # View
  frontend:
    build: ./frontend

  # Microservices
  auth-service:
    build: ./auth-service
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=enrollment_db
      - DB_HOST_PRIMARY=db-primary
      - DB_HOST_REPLICA=db-replica

  course-service:
    build: ./course-service
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=enrollment_db
      - DB_HOST_PRIMARY=db-primary
      - DB_HOST_REPLICA=db-replica
      
  grade-service:
    build: ./grade-service
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=enrollment_db
      - DB_HOST_PRIMARY=db-primary
      - DB_HOST_REPLICA=db-replica
    depends_on:
      - db-primary

  # Db Layers
  db-primary:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enrollment_db
    volumes:
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-replica:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enrollment_db
    volumes:
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - db-primary