events {}

http {
    upstream auth_nodes {
        server auth-service:3000;
    }

    upstream course_nodes {
        server course-service:3001;
    }

    server {
        listen 80;

        # 1. Route for the "View" (Frontend)
        location / {
            proxy_pass http://frontend:80;
        }

        # 2. Route for Auth Service
        location /api/auth {
            proxy_pass http://auth_nodes;
            proxy_set_header Host $host;
        }

        # 3. Route for Course Service
        location /api/courses {
            proxy_pass http://course_nodes;
            proxy_set_header Host $host;
        }
    }
}